[tool.poetry]
name = "poetry-multiproject-plugin"
version = "0.1.0"
description = "A Poetry plugin that makes it possible to build projects with custom TOML files."
authors = ["David Vujic <david@vujic.se>"]
homepage = "https://github.com/davidvujic/poetry-multiproject-plugin"
repository = "https://github.com/davidvujic/poetry-multiproject-plugin"
readme = "README.md"
packages = [{include = "poetry_multiproject_plugin"}]

[tool.poetry.plugins."poetry.application.plugin"]
poetry-multiproject-plugin = "poetry_multiproject_plugin:MultiProjectPlugin"

[tool.poetry.dependencies]
python = "^3.10"
poetry = {version = "^1.2.0a2", allow-prereleases = true}

[tool.poetry.dev-dependencies]
cachecontrol = "0.12.10"
cleo = "1.0.0a4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"